export const TEST = 'TEST';
export const GET_PRODUCT_FORM_DATA = 'GET_PRODUCT_FORM_DATA';
export const GET_PRODUCT_FORM_DATA_SUCCESS = 'GET_PRODUCT_FORM_DATA_SUCCESS';
export const GET_PRODUCT_FORM_DATA_FAILED = 'GET_PRODUCT_FORM_DATA_FAILED';

export const UPDATE_PRODUCT_FORM_DATA = 'UPDATE_PRODUCT_FORM_DATA';